[package]
name = "mlang-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mlang = { path = "core" }
wasm-bindgen = "0.2"

[profile.release]
lto = true
opt-level = 's'
